"""Investor PDF rendering.

Layout is three parts: a cover page carrying the profile and the registry
verification badge, a page of charts, and the model's Markdown analysis
converted to flowables. The Markdown conversion is intentionally small — it
handles the headings, bold lines and bullets the report prompt asks for, and
treats anything else as body text.
"""

from __future__ import annotations

import io
import re
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus import (
    Image as RLImage,
)

from finagent.services import charts

ACCENT = colors.HexColor("#6366f1")
INK = colors.HexColor("#1e293b")
SLATE = colors.HexColor("#334155")
MUTED = colors.HexColor("#94a3b8")
BORDER = colors.HexColor("#e2e8f0")
SURFACE = colors.HexColor("#f1f5f9")
SUCCESS = colors.HexColor("#16a34a")
DANGER = colors.HexColor("#dc2626")

DISCLAIMER = (
    "This report was generated by FinAgent. Market figures shown in the charts are "
    "illustrative baselines, and the written analysis is model-generated. Confirm "
    "material facts with primary sources before making an investment decision."
)


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("Title_", parent=base["Title"], fontSize=26,
                                textColor=ACCENT, spaceAfter=6,
                                fontName="Helvetica-Bold", alignment=TA_CENTER),
        "subtitle": ParagraphStyle("Subtitle_", parent=base["Normal"], fontSize=13,
                                   textColor=MUTED, spaceAfter=4, alignment=TA_CENTER),
        "section": ParagraphStyle("Section_", parent=base["Heading2"], fontSize=14,
                                  textColor=ACCENT, spaceBefore=14, spaceAfter=6,
                                  fontName="Helvetica-Bold"),
        "body": ParagraphStyle("Body_", parent=base["Normal"], fontSize=10,
                               textColor=INK, leading=16, alignment=TA_JUSTIFY,
                               spaceAfter=6),
        "label": ParagraphStyle("Label_", parent=base["Normal"], fontSize=9,
                                textColor=ACCENT, fontName="Helvetica-Bold"),
        "value": ParagraphStyle("Value_", parent=base["Normal"], fontSize=10,
                                textColor=INK, leading=14),
        "chart": ParagraphStyle("Chart_", parent=base["Normal"], fontSize=11,
                                textColor=SLATE, fontName="Helvetica-Bold",
                                spaceAfter=6, spaceBefore=10),
        "disclaimer": ParagraphStyle("Disclaimer_", parent=base["Normal"], fontSize=8,
                                     textColor=MUTED, alignment=TA_CENTER, spaceBefore=8),
    }


def _strip_markdown(line: str) -> str:
    line = re.sub(r"\*\*(.*?)\*\*", r"\1", line)
    return re.sub(r"\*(.*?)\*", r"\1", line)


def _markdown_flowables(text: str, styles: dict[str, ParagraphStyle]) -> list:
    """Convert the model's Markdown into ReportLab flowables."""
    bold = ParagraphStyle("Bold_", parent=styles["body"], fontName="Helvetica-Bold",
                          fontSize=11, textColor=SLATE)
    bullet = ParagraphStyle("Bullet_", parent=styles["body"], leftIndent=12, spaceAfter=3)

    flowables: list = []
    for raw in text.split("\n"):
        line = raw.strip()
        if not line:
            flowables.append(Spacer(1, 4))
            continue

        clean = _strip_markdown(line)
        if line.startswith("#"):
            flowables.append(Paragraph(line.lstrip("#").strip(), styles["section"]))
        elif line.startswith("**") and line.endswith("**"):
            flowables.append(Paragraph(clean, bold))
        elif line.startswith(("- ", "* ")):
            flowables.append(Paragraph(f"• {clean[2:].strip()}", bullet))
        else:
            flowables.append(Paragraph(clean, styles["body"]))
    return flowables


def _profile_table(startup: dict, styles: dict[str, ParagraphStyle]) -> Table:
    verification = startup.get("verification", {})
    rows = [
        ["Startup Name", startup.get("name", "N/A")],
        ["Domain / Industry", startup.get("domain", "N/A")],
        ["Startup ID", startup.get("startup_id", "N/A")],
        ["Registered", startup.get("created_at", "N/A")],
    ]
    if verification.get("mca_verified"):
        rows += [
            ["CIN", verification.get("cin", "N/A")],
            ["MCA Company Name", verification.get("company_name", "N/A")],
            ["Company Status", verification.get("company_status", "N/A")],
            ["Directors", ", ".join(verification.get("directors", [])) or "N/A"],
        ]

    table = Table(
        [[Paragraph(label, styles["label"]), Paragraph(str(value), styles["value"])]
         for label, value in rows],
        colWidths=[4 * cm, 12 * cm],
    )
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), SURFACE),
        ("BACKGROUND", (1, 0), (1, -1), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return table


def build_pdf(startup: dict, analysis_text: str) -> bytes:
    """Render the full investor report and return it as PDF bytes."""
    styles = _styles()
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
        title=f"FinAgent Evaluation — {startup.get('name', 'Startup')}",
        author="FinAgent",
    )

    story: list = [
        Spacer(1, 1.5 * cm),
        Paragraph("FinAgent Startup Evaluation Report", styles["title"]),
        Paragraph(
            "Powered by the LangGraph RAG pipeline &nbsp;|&nbsp; "
            f"Generated {datetime.now().strftime('%B %d, %Y')}",
            styles["subtitle"],
        ),
        Spacer(1, 0.4 * cm),
        HRFlowable(width="100%", thickness=2, color=ACCENT, spaceAfter=12),
    ]

    # Registry verification badge.
    verified = startup.get("verification", {}).get("mca_verified", False)
    story.append(Paragraph(
        "MCA VERIFIED" if verified else "MCA NOT VERIFIED",
        ParagraphStyle("Badge_", parent=styles["body"], fontSize=10,
                       textColor=SUCCESS if verified else DANGER,
                       fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=8),
    ))

    story += [_profile_table(startup, styles), Spacer(1, 0.5 * cm)]

    story.append(Paragraph("Product Description", styles["section"]))
    story.append(Paragraph(startup.get("description", "N/A"), styles["body"]))
    story.append(Paragraph("Team", styles["section"]))
    story.append(Paragraph(startup.get("team", "N/A"), styles["body"]))
    if startup.get("extras"):
        story.append(Paragraph("Additional Information", styles["section"]))
        story.append(Paragraph(str(startup["extras"]), styles["body"]))

    # ── Charts ────────────────────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("Market Analysis & Visualisations", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=10))

    for caption, png in charts.all_charts(startup):
        story.append(Paragraph(caption, styles["chart"]))
        story.append(RLImage(io.BytesIO(png), width=15 * cm, height=8.5 * cm))
        story.append(Spacer(1, 0.6 * cm))

    # ── Model analysis ────────────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("AI-Generated Investor Report", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=10))
    story += _markdown_flowables(analysis_text, styles)

    story += [
        Spacer(1, 1 * cm),
        HRFlowable(width="100%", thickness=1, color=BORDER),
        Paragraph(DISCLAIMER, styles["disclaimer"]),
    ]

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def filename_for(startup: dict) -> str:
    name = (startup.get("name") or "startup").replace(" ", "_")
    return f"report_{name}_{startup.get('startup_id', '')[:8]}.pdf"
